apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
     containers:
       - name: nginx
         image: nginx
         ports: 
          - containerPort: 80
         env: 
          - name: GREETING
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: GREETING
          - name: APP_ENV
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: APP_ENV
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD